version: '3'


services:
  digitransit-proxy:
    image: {{ digitransit["images"]["proxy"] }}
    container_name: digitransit-proxy
    restart: on-failure:5
    networks:
      - digitransit
    ports:
      - {{ digitransit_port }}:8080
    volumes:
      - ${PWD}/logs:/var/log/nginx
  opentripplanner:
    image: {{ digitransit["images"]["otp"] }}
    restart: on-failure:5
    container_name: opentripplanner
    logging:
      driver: journald
    environment:
      - ROUTER_NAME=hb
      - ROUTER_DATA_CONTAINER_URL=http://opentripplanner-data-con:8080
      - API_URL=https://{{ api_hostname }}/routing/v1/
      - ENCRYPTION_SECRET_KEY={{ encryption_secret_key }}
      - JAVA_OPTS=-Xmx8G
      - ASTAR_STATISTICS={{ a_star_statistics }}
    networks:
      - digitransit
  opentripplanner-data-con:
    image: {{ digitransit["images"]["data_container"] }}
    restart: on-failure:5
    logging:
      driver: journald
    networks:
      - digitransit
  digitransit-ui:
    image: {{ digitransit["images"]["ui"] }}
    restart: on-failure
    container_name: digitransit-ui
    networks:
      - digitransit
    logging:
      driver: journald
    environment:
      - CONFIG={{ digitransit_config }}
      - GEOCODING_BASE_URL=https://{{ api_hostname }}/geocoding/v1
      - API_URL=https://{{ api_hostname }}
      - MAP_URL={{ map_url }}
      - SEMI_TRANSPARENT_MAP_URL={{ semi_transparent_map_url }}
      - MATOMO_URL={{ matomo_url }}
      - NODE_ENV=production
      - FAHRGEMEINSCHAFT_API_KEY={{ fahrgemeinschaft_api_key }}
      - FAHRGEMEINSCHAFT_AUTH_KEY={{ fahrgemeinschaft_auth_key }}
  hsl-map-server:
    image: {{ digitransit["images"]["map_server"] }}
    container_name: hsl-map-server
    restart: on-failure:5
    networks:
      - digitransit
    logging:
      driver: journald
    environment:
      - PARK_API_URL=https://{{ api_hostname }}/parkapi.json
      - OTP_URL=opentripplanner:8080/otp/routers/hb/index/graphql
    logging:
      driver: journald
  photon-pelias-adapter:
    image: stadtulm/photon-pelias-adapter:47c824d
    container_name: photon-pelias-adapter
    logging:
      driver: journald
    restart: on-failure:5
    networks:
      - digitransit
    environment:
      - PHOTON_URL={{ photon_url }}

networks:
  digitransit:
    # all default


