version: '3'

services:
  digitransit-proxy:
    image: {{ digitransit["images"]["proxy"] }}
    networks:
      - digitransit
    ports:
      - {{ digitransit_port }}:8080
    volumes:
      - ${PWD}/logs:/var/log/nginx
  opentripplanner-hb:
    image: {{ digitransit["images"]["otp"] }}
    environment:
      - ROUTER_NAME=hb
      - ROUTER_DATA_CONTAINER_URL=http://opentripplanner-data-con-hb:8080
      - API_URL=https://{{ api_hostname }}/routing/v1/
      - ENCRYPTION_SECRET_KEY={{ encryption_secret_key }}
    networks:
      - digitransit
  opentripplanner-data-con-hb:
    image: {{ digitransit["images"]["data_container"] }}
    networks:
      - digitransit
  digitransit-ui:
    image: {{ digitransit["images"]["ui"] }}
    networks:
      - digitransit
    environment:
      - CONFIG=hb
      - GEOCODING_BASE_URL=https://{{ api_hostname }}/geocoding/v1
      - API_URL=https://{{ api_hostname }}
      - MAP_URL={{ map_url }}
      - MAP_KEY={{ map_key }}
      - MATOMO_URL={{ matomo_url }}
      - ENABLE_CARPOOL={{ enable_carpool }}
  hsl-map-server:
    image: {{ digitransit["images"]["map_server"] }}
    networks:
      - digitransit
    environment:
      - PARK_API_URL=https://{{ api_hostname }}/parkapi.json
      - OTP_URL=opentripplanner-hb:8080/otp/routers/hb/index/graphql
  photon-pelias-adapter:
    image: stadtulm/photon-pelias-adapter:latest
    networks:
      - digitransit
    environment:
      - PHOTON_URL=https://api.mfdz.de/photon/

networks:
  digitransit:
    # all default


