version: '3'

services:
  digitransit-proxy:
    image: transportkollektiv/digitransit-proxy:hb
    networks:
      - digitransit
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/logs:/var/log/nginx
  opentripplanner-hb:
    image: mfdz/opentripplanner:latest
    environment:
      - ROUTER_NAME=hb
      - ROUTER_DATA_CONTAINER_URL=http://opentripplanner-data-con-hb:8080
    networks:
      - digitransit
  opentripplanner-data-con-hb:
    image: mfdz/opentripplanner-data-container-hb:latest
    networks:
      - digitransit
  digitransit-ui:
    image: mfdz/digitransit-ui:latest
    networks:
      - digitransit
    environment:
      - CONFIG=hb
      - GEOCODING_BASE_URL=https://{{ hostname }}/geocoding/v1
      - API_URL=https://{{ hostname }}
  hsl-map-server:
    image: mfdz/hsl-map-server:latest
    networks:
      - digitransit
    environment:
      - OTP_URL=opentripplanner-hb:8080/otp/routers/hb/index/graphql
  photon-pelias-adapter:
    image: stadtulm/photon-pelias-adapter:latest
    networks:
      - digitransit
    environment:
      - PHOTON_URL=https://api.mfdz.de/photon/

networks:
  digitransit:
    # all default

