---
- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart tileserver
  service:
    name: tileserver
    state: restarted

- name: Restart monit
  service:
    name: monit
    state: restarted
