- src: geerlingguy.docker
  version: 2.6.0
- src: geerlingguy.certbot
  version: 3.0.3
- src: geerlingguy.swap
  version: 1.0.1
- src: geerlingguy.firewall
  version: 2.5.0
- src: dev-sec.ssh-hardening
  version: 9.0.0
