---
- name: Check nginx conf
  command: "/usr/sbin/nginx -t"
  become: yes
  listen: "Restart nginx"

- name: Restart nginx service
  service:
    name: nginx
    state: restarted
  listen: "Restart nginx"

- name: Restart nominatim
  service:
    name: nominatim
    state: restarted

- name: Restart photon
  service:
    name: photon
    state: restarted

- name: Restart photon-pelias-adapter
  service:
    name: photon-pelias-adapter
    state: restarted


