---
- name: Create graphs directory
  file:
    path: /var/data-builder/graphs
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  notify: Restart data-builder
  with_items:
    - data-builder.service
    - data-builder.timer

- name: Start data-builder.timer
  systemd: state=started name=data-builder.timer daemon_reload=yes
