---
- name: Create data directory
  file:
    path: /var/gtfs-hub
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - gtfs-hub.service
    - gtfs-hub.timer

- name: Start data-builder.timer
  systemd:
    name: gtfs-hub.timer
    enabled: yes
    daemon_reload: yes
