---
- name: Install base packages
  package:
    name:
      - python-docker
    state: present

- name: Create photon network
  docker_network:
    name: photon-network

- name: Install systemd files for nominatim-update
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - nominatim.service
    - nominatim-update.service
    - nominatim-update.timer
    - photon.service
  notify:
    # photon.service dependens on nominatim.service so it's restarted, too.
    - Restart nominatim

- name: Start nomimatim and photon services
  systemd: state=started name="{{ item }}" enabled=yes daemon_reload=yes
  with_items:
    - nominatim.service
    - nominatim-update.timer
    - photon.service

- name: Copy photon nginx site conf
  template: src=photon-site.conf dest=/etc/nginx/sites-available/{{ item }}.conf
  with_items:
    - "{{ photon_hostname }}"
  notify: Restart nginx

- name: Symlink to sites-available
  file:
    src: /etc/nginx/sites-available/{{ item }}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
    state: link
  with_items:
    - "{{ photon_hostname }}"
  notify: Restart nginx


