---
- name: Install base packages
  package:
    name:
      - python-docker
    state: present

- name: Create photon network
  docker_network:
    name: photon-network

- name: Install systemd files for nominatim-update
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - nominatim.service
    - nominatim-update.service
    - nominatim-update.timer

- name: Start nomimatim-update.timer
  systemd: state=started name="{{ item }}" enabled=yes daemon_reload=yes
  with_items:
    - nominatim.service
    - nominatim-update.timer

- name: Import and run photon
  docker_container:
    name: photon
    image: lehrenfried/photon:latest
    networks:
      - name: photon-network
    volumes:
      - photon-data-dach:/photon/photon_data:rw
    ports:
      - "2322:2322"
    env:
      NOMINATIM_PORT_5432_TCP_ADDR: nominatim
      # this is purposefully set to a directory as otherwise the container tries to import a JSON file
      # if the "dump" is a directory it does the import through postgres directly
      JSON_DUMP_FILE: "/etc/"
      AUTOMATIC_UPDATES: "true"

- name: Copy photon nginx site conf
  template: src=photon-site.conf dest=/etc/nginx/sites-available/{{ item }}.conf
  with_items:
    - "{{ photon_hostname }}"
  notify: Restart nginx

- name: Symlink to sites-available
  file:
    src: /etc/nginx/sites-available/{{ item }}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
    state: link
  with_items:
    - "{{ photon_hostname }}"
  notify: Restart nginx


