version: '3'

services:
  opentripplanner:
    image: {{ digitransit["images"]["otp"] }}
    restart: on-failure:5
    container_name: opentripplanner
    logging:
      driver: journald
    ports:
      - {{otp_port}}:8080
    command: --load --serve graph
    environment:
      - ROUTER_NAME=hb
      - API_URL=https://{{ api_hostname }}/otp/routers/default/
      - ENCRYPTION_SECRET_KEY={{ encryption_secret_key }}
      - JAVA_OPTS=-Xmx8G
    volumes:
      - /var/graph-build/latest/:/opt/opentripplanner/graph/

{% for item in digitransit_ui %}
  digitransit-ui-{{ item["config"] }}:
    image: {{ item["image"] }}
    restart: on-failure
    container_name: digitransit-ui-{{ item["config"]}}
    ports:
      - {{ item["port"] }}:8080
    networks:
      - digitransit
    logging:
      driver: journald
    environment:
      - CONFIG={{ item["config"] }}
      - GEOCODING_BASE_URL={{ photon_url }}/pelias/v1
      - API_URL=https://{{ api_hostname }}
      - MAP_URL={{ map_url }}
      - SEMI_TRANSPARENT_MAP_URL={{ semi_transparent_map_url }}
      - NODE_ENV=production
      - FAHRGEMEINSCHAFT_API_KEY={{ fahrgemeinschaft_api_key }}
      - FAHRGEMEINSCHAFT_AUTH_KEY={{ fahrgemeinschaft_auth_key }}
{% endfor %}

  hsl-map-server:
    image: {{ digitransit["images"]["map_server"] }}
    container_name: hsl-map-server
    restart: on-failure:5
    networks:
      - digitransit
    ports:
      - {{ map_server_port }}:8080
    environment:
      - PARK_API_URL=https://api.stadtnavi.de/herrenberg/parking/parkapi.json
      - OTP_URL=https://{{ api_hostname }}/otp/routers/default/index/graphql
      - CIFS_URL=https://api.stadtnavi.de/herrenberg/road-disruptions/road-disruptions.cifs.json
      - WEATHER_STATIONS_URL=https://api.stadtnavi.de/herrenberg/weather/weather.geojson
      - CHARGING_STATIONS_URL=https://api.stadtnavi.de/herrenberg/charging-stations/charging-stations.geojson
    logging:
      driver: journald

  graphiql:
    image: corykitchens/graphiql:latest
    container_name: graphiql
    restart: on-failure:5
    networks:
      - digitransit
    ports:
      - {{ graphiql_port }}:4000
    environment:
      - API_URL=https://api.dev.stadtnavi.eu/routing/v1/router/index/graphql
    logging:
      driver: journald

networks:
  digitransit:
    # all default
