---
- name: Install base packages
  package:
    name:
      - htop
      - tree
      - neovim
      - cron-apt
      - ripgrep
      - silversearcher-ag
    state: present

- name: Install global aliases
  template: src=alias.sh dest=/etc/profile.d/

- name: Adding existing user '{{ item }}' to group sudo
  user:
    name: '{{ item }}'
    groups: docker
    append: yes
  with_items: "{{ users }}"
