---
- name: Install base packages
  package:
    name:
      - htop
      - glances
      - tree
      - neovim
      - cron-apt
      - silversearcher-ag
      - autojump
      - jq
      - zsh
    state: present

- name: Install global aliases
  template: src=alias.sh dest=/etc/profile.d/

- hostname:
    name: "{{ server_name }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ server_name }}"

- name: Set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: Adding existing user '{{ item }}' to group sudo
  user:
    name: '{{ item }}'
    groups:
      - docker
      - systemd-journal
    shell: /bin/zsh
    append: yes
  with_items: "{{ users }}"


- name: Install systemd files for docker-prune
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - docker-prune.service
    - docker-prune.timer

- name: Start docker-prune.timer
  systemd:
    name: docker-prune.timer
    state: started
    enabled: yes
    daemon_reload: yes

- name: Copy send-to-matrix script
  template:
    src: "{{ item }}"
    dest: /usr/local/bin
    mode: 711
  with_items:
    - send-to-matrix

- name: Install journald.conf
  template: src={{ item }} dest=/etc/systemd/
  with_items:
    - journald.conf
  notify: Restart systemd-journald


