---
- name: Install base packages
  package:
    name:
      - python-docker
    state: present

- name: Create photon network
  docker_network:
    name: photon-network

- name: Install systemd files for nominatim-update
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - photon-new.service
  notify:
    # photon.service dependens on nominatim.service so it's restarted, too.
    - Restart photon-new

- name: Start photon-new service
  systemd: state=started name="{{ item }}" enabled=yes daemon_reload=yes
  with_items:
    - photon-new.service
