---
- name: Install packages
  package:
    name:
      - dnsmasq # for some reason outgoing traffic to port 53 (DNS) is blocked and we need to use this package to fake a local DNS server
      - nginx
      - pyosmium
    state: present

- name: Create tile cache directory
  file:
    path: /var/cache/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Copy nginx site conf
  template: src=nginx-site.conf dest=/etc/nginx/sites-enabled/{{item}}.conf
  with_items:
    - "{{ tiles_hostname }}"
  notify: Restart nginx


- name: Create graphs directory
  file:
    path: /var/tileserver/
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install config and script files
  template: src={{ item }} dest=/var/tileserver/
  with_items:
    - streets.json
    - satellite-overlay.json
    - tileserver-config.json
  notify: Restart tileserver

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - tileserver.service
    - tileserver-restart.service
    - tileserver-restart.timer
  notify: Restart tileserver

- name: Start tileserver and restart every night
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - tileserver.service
    - tileserver-restart.timer

- apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main contrib non-free"
    state: present
    update_cache: yes

- name: Install monit from backports
  apt:
    name: monit
    state: present
    default_release: buster-backports

- name: Copy monit file
  template: src=monit.check dest=/etc/monit/conf-enabled/tileserver.cfg
  notify: Restart monit


