---
- name: Install base packages
  package:
    name:
      - pyosmium
    state: present


- name: Create graphs directory
  file:
    path: /var/tileserver/
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install config and script files
  template: src={{ item }} dest=/var/tileserver/
  with_items:
    - streets.json
    - tileserver-config.json
  notify: Restart tileserver

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - tileserver.service
  notify: Restart tileserver

- name: Start tileserver
  systemd:
    name: tileserver.service
    state: started
    enabled: yes
    daemon_reload: yes

