---
- name: Install base packages
  package:
    name:
      - pyosmium
      - nginx
    state: present

- name: Create tile cache directory
  file:
    path: /var/cache/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Copy nginx site conf
  template: src=nginx-site.conf dest=/etc/nginx/sites-enabled/{{item}}.conf
  with_items:
    - tiles.leonard.io
  notify: Restart nginx


- name: Create graphs directory
  file:
    path: /var/tileserver/
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install config and script files
  template: src={{ item }} dest=/var/tileserver/
  with_items:
    - streets.json
    - satellite-overlay.json
    - tileserver-config.json
  notify: Restart tileserver

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - tileserver.service
    - tileserver-restart.service
    - tileserver-restart.timer
  notify: Restart tileserver

- name: Start tileserver and restart every night
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - tileserver.service
    - tileserver-restart.timer

